auto: true

title : Rails Beginners Lesson by Minami.rb

safe:        true
destination: ./_site
lsi:         false
pygments:    true

server_port: 4000
markdown:    kramdown
permalink:   pretty

url:      http://minamirb.github.com/rails_beginners_lesson/
baseurl: /rails_beginners_lesson/